networks:
  feruNT:

services:
  app:
    container_name: books_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9000
    depends_on:
      - db
    networks:
      feruNT:

  db:
    container_name: books_db
    image: postgres:latest

    environment:
      POSTGRES_USER: feruu
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ferudbb
    ports:
      - 5432:5432
    networks:
      feruNT:
